/**
 * Loopback client tests (node:test, no vscode): a FAKE daemon speaking the exact JSON-lines protocol
 * ({op,args,token}\n -> one line -> close) on the real per-OS transport (named pipe on Windows, UDS on
 * POSIX). Proves the M8 exit-criteria client legs: token auth round-trip, approval round-trip wire
 * shape, DENIED_STALE_FENCE surfacing as a STRUCTURED payload (never a throw), the clean
 * daemon-unreachable state, the cross-platform TCP fallback, and the pipe-name parity vector against
 * loopback.py's workspace_hash. The in-flight primary timeout leg runs on both transports.
 */

import assert from "node:assert/strict";
import { after, before, test } from "node:test";
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as net from "node:net";
import * as path from "node:path";

import { DaemonUnreachable, MAX_LINE_BYTES, readToken, request, runtimeDir, workspaceHash } from "../../extension/src/protocol";
import { fakeRepoRoot, listenPathFor, startFakeDaemon, TOKEN, WIN } from "./fakeDaemon";
import { makeTestTempDir } from "./tempRoot";

let root: string;
let server: net.Server | undefined;

before(async () => {
  root = fakeRepoRoot();
  server = (
    await startFakeDaemon(listenPathFor(root), {
      status: { status: "OK", running: true, engines: ["codex", "local_llm"], node_id: null },
      approve: { status: "OK", id: "ap_1", state: "approved", decided_by: "human" },
      attach: { status: "DENIED", code: "DENIED_STALE_FENCE", current_epoch: 7 },
    })
  ).server;
});

after(() => server?.close());

test("workspace hash parity vector matches loopback.py (win32 form)", { skip: !WIN }, () => {
  // Golden vector generated by kaizen_components.orchestration.loopback.workspace_hash on this repo.
  assert.equal(workspaceHash("D:\\dev\\agent-kaizen", "win32"), "37831eee9bf77bf5");
});

test("workspace hash algorithm: sha256(resolved[, lowercased on win32])[:16]", () => {
  const p = path.resolve("/some/Repo");
  const expect = (text: string) => crypto.createHash("sha256").update(text, "utf-8").digest("hex").slice(0, 16);
  assert.equal(workspaceHash("/some/Repo", "linux"), expect(p));
  assert.equal(workspaceHash("/some/Repo", "win32"), expect(p.toLowerCase()));
});

test("status round-trip with token auth", async () => {
  assert.equal(readToken(root), TOKEN);
  const resp = await request(root, "status");
  assert.equal(resp.status, "OK");
  assert.deepEqual(resp.engines, ["codex", "local_llm"]);
});

test("approval round-trip carries the wire shape the daemon expects", async () => {
  const resp = await request(root, "approve", { approval_id: "ap_1", decision: "approve" });
  assert.equal(resp.status, "OK");
  assert.equal(resp.state, "approved");
});

test("stale epoch attach surfaces DENIED_STALE_FENCE as a structured payload, not a throw", async () => {
  const resp = await request(root, "attach", { session_id: "s1", expected_owning_node: "nA", expected_node_epoch: 3 });
  assert.equal(resp.status, "DENIED");
  assert.equal(resp.code, "DENIED_STALE_FENCE");
});

test("an oversized UTF-8 request is denied locally without reaching the daemon", async () => {
  const localRoot = fakeRepoRoot();
  const daemon = await startFakeDaemon(listenPathFor(localRoot), { status: { status: "OK" } });
  try {
    // A multibyte character proves the guard counts UTF-8 bytes, not JavaScript code units.
    const resp = await request(localRoot, "status", { text: "\u20ac".repeat(MAX_LINE_BYTES) });
    assert.deepEqual(resp, {
      status: "DENIED",
      code: "PAYLOAD_TOO_LARGE",
      retryable: false,
      limit_bytes: MAX_LINE_BYTES,
    });
    assert.equal(daemon.requests.length, 0);
  } finally {
    daemon.close();
  }
});

test("an oversized daemon reply resolves as an exact structured denial", async () => {
  const largeRoot = fakeRepoRoot();
  const daemon = await startFakeDaemon(listenPathFor(largeRoot), {
    status: { status: "OK", text: "x".repeat(MAX_LINE_BYTES) },
  });
  try {
    assert.deepEqual(await request(largeRoot, "status"), {
      status: "DENIED",
      code: "PAYLOAD_TOO_LARGE",
      retryable: false,
      limit_bytes: MAX_LINE_BYTES,
    });
  } finally {
    daemon.close();
  }
});

test("wrong token is refused by the daemon (auth teeth)", async () => {
  const wrongRoot = fakeRepoRoot();
  const daemon = await startFakeDaemon(listenPathFor(wrongRoot), { status: { status: "OK" } });
  fs.writeFileSync(path.join(runtimeDir(wrongRoot), "control.token"), "WRONG", "utf-8");
  try {
    const resp = await request(wrongRoot, "status");
    assert.equal(resp.code, "DENIED_LOOPBACK_AUTH");
  } finally {
    daemon.close();
  }
});

test("no daemon => clean DaemonUnreachable, never a hang or crash", async () => {
  const dead = fakeRepoRoot(); // token exists but nothing listens
  await assert.rejects(request(dead, "status", {}, 1500), DaemonUnreachable);
});

test("missing token file => clean DaemonUnreachable", async () => {
  const bare = makeTestTempDir("kaizen-ext-bare-");
  await assert.rejects(request(bare, "status"), DaemonUnreachable);
});

test("a malformed daemon reply becomes a readable DaemonUnreachable", async () => {
  const malformedRoot = fakeRepoRoot();
  const malformed = net.createServer((connection) => {
    connection.once("data", () => connection.end("not-json\n"));
  });
  await new Promise<void>((resolve, reject) => {
    malformed.once("error", reject);
    malformed.listen(listenPathFor(malformedRoot), resolve);
  });
  try {
    await assert.rejects(request(malformedRoot, "status"), (error: unknown) =>
      error instanceof DaemonUnreachable && /malformed reply/.test(error.message));
  } finally {
    await new Promise<void>((resolve) => malformed.close(() => resolve()));
  }
});

test("TCP fallback via control.addr when the primary endpoint is absent", async () => {
  const tcpRoot = fakeRepoRoot(); // no pipe listener for THIS root -> falls back to control.addr
  const tcp = await startFakeDaemon(0, { ping: { status: "OK", pong: true } });
  const addr = tcp.server.address() as net.AddressInfo;
  fs.writeFileSync(path.join(runtimeDir(tcpRoot), "control.addr"), `127.0.0.1:${addr.port}`, "utf-8");
  try {
    const resp = await request(tcpRoot, "ping");
    assert.equal(resp.pong, true);
  } finally {
    tcp.close();
  }
});

test("control.addr rejects non-loopback hosts and invalid ports before connecting", async () => {
  const invalidRoot = fakeRepoRoot();
  for (const address of ["localhost:1234", "192.0.2.1:1234", "127.0.0.1:0", "127.0.0.1:65536"]) {
    fs.writeFileSync(path.join(runtimeDir(invalidRoot), "control.addr"), address, "utf-8");
    await assert.rejects(request(invalidRoot, "status", {}, 100), (error: unknown) =>
      error instanceof DaemonUnreachable && /malformed control\.addr/.test(error.message));
  }
});

test("in-flight primary timeout is one-shot and never replays the request over TCP", async () => {
  const timeoutRoot = fakeRepoRoot();
  let primaryRequests = 0;
  const hangingPrimary = net.createServer((connection) => {
    let counted = false;
    connection.on("data", () => {
      if (!counted) {
        counted = true;
        primaryRequests += 1;
      }
      // Deliberately accept the authenticated request without replying: it is now in flight.
    });
  });
  await new Promise<void>((resolve, reject) => {
    hangingPrimary.once("error", reject);
    hangingPrimary.listen(listenPathFor(timeoutRoot), () => resolve());
  });
  const tcp = await startFakeDaemon(0, { slow: { status: "OK", replayed: true } });
  const addr = tcp.server.address() as net.AddressInfo;
  fs.writeFileSync(path.join(runtimeDir(timeoutRoot), "control.addr"), `127.0.0.1:${addr.port}`, "utf-8");
  const started = Date.now();
  try {
    await assert.rejects(request(timeoutRoot, "slow", {}, 250), /loopback timeout/);
    assert.equal(primaryRequests, 1);
    assert.equal(tcp.requests.length, 0, "an in-flight request must never be duplicated on fallback TCP");
    assert.ok(Date.now() - started < 2_500, "one overall deadline must not become two full timeouts");
  } finally {
    hangingPrimary.close();
    tcp.close();
  }
});
